### ISSUE TITLE
'Cannot read property messages of undefined' error

### ISSUE THREAD

**Issue by mmixu** [theLAZYmd/LAZYbot#66]
LAZYbot spams an error message whenever an ’undefined’ user says something
![6 discorderror](https://user-images.githubusercontent.com/35734373/56028876-d0ce5d80-5d21-11e9-8d62-793f5be6d217.png)

**Comment by theLAZYmd** [comment]
Think that was a specific issue with HighestCliff, resolved with better dbuser managing
