### ISSUE TITLE
!shield superblitz considered as !shield blitz

### ISSUE THREAD

**Issue by mmixu** [theLAZYmd/LAZYbot#93]
`!shield superblitz` (3+0) returns as `!shield blitz` (5+0)

https://i.imgur.com/0PqBs7P.png

**Comment by mmixu** [comment]
Same with hyperbullet and bullet

**Comment by theLAZYmd** [comment]
Closed with https://github.com/theLAZYmd/LAZYbot/commit/ff08c39c43de61e710b0422d5eafae006d9c2791
